// "web kit" export: everything a website needs to draw the effect live —
// source image, optional subject mask, poster, settings JSON, the engine as one
// standalone module, a worker, and a React component — zipped together.
// The engine bundled here is the same code the tool runs, so output matches.

import { drawDesign } from './render.js';

// Engine modules in dependency order. Each is wrapped in its own scope.
const MODULES = ['tone', 'lattice', 'geometry', 'engine', 'runtime'];

export async function bundleEngine() {
  const parts = [
    '// halftone-engine.js — generated by Halftoner. Standalone ES module, no dependencies.',
    '// Exports: createEngine, loadImage, prepareSource, computeHalftone, drawHalftone, fieldLayers, paint',
    '',
  ];
  for (const m of MODULES) {
    let src = await (await fetch(new URL(`./${m}.js`, import.meta.url), { cache: 'no-store' })).text();
    const names = [];
    src = src.replace(/^import\s*\{([^}]*)\}\s*from\s*'\.\/(\w+)\.js';?[ \t]*$/gm,
      (_, list, mod) => `const {${list.replace(/\s+as\s+/g, ': ')}} = __${mod};`);
    src = src.replace(/^export\s+(async\s+function|function|const|let|class)\s+(\w+)/gm,
      (_, kw, name) => { names.push(name); return `${kw} ${name}`; });
    if (/^\s*(import|export)\b/m.test(src)) throw new Error(`can't bundle ${m}.js (unexpected import/export)`);
    parts.push(`// ---------------------------------------------------------------- ${m}.js`);
    parts.push(`const __${m} = (() => {\n${src.trim()}\nreturn { ${names.join(', ')} };\n})();\n`);
  }
  parts.push('export const { createEngine } = __engine;');
  parts.push('export const { loadImage, prepareSource, computeHalftone, drawHalftone, fieldLayers, paint } = __runtime;');
  return parts.join('\n') + '\n';
}

const WORKER = `// halftone-worker.js — generated by Halftoner. Computes the halftone off the main thread.
import { createEngine } from './halftone-engine.js';

self.onmessage = (e) => {
  try {
    const engine = createEngine();
    engine.setSource({ key: 'kit', ...e.data.source });
    self.postMessage({ result: engine.render(e.data.config, false) });
  } catch (err) {
    self.postMessage({ error: String((err && err.message) || err) });
  }
};
`;

function component({ W, H, slug, hasMask, ink, paper, summary }) {
  return `'use client';
// Halftone — generated by Halftoner (${summary}).
//
// Draws the halftone live from the source image with the settings in
// halftone.config.json: sharp at any size, recomputed if you pass settings.
// A small poster image shows instantly while the dots are computed.
//
//   import Halftone from '@/components/halftone/Halftone';
//   <Halftone alt="…" className="w-full" />
//   <Halftone fit="cover" position="70% 50%" style={{ height: '100svh' }} />
//   <Halftone settings={{ cell: 12, angle: 0 }} />          // live overrides
//   <Halftone ink="currentColor" paper={null} />             // follow CSS color
import { useEffect, useMemo, useRef, useState } from 'react';
import { loadImage, prepareSource, computeHalftone, drawHalftone, fieldLayers } from './halftone-engine.js';
import baseConfig from './halftone.config.json';

const ASSETS = '/halftone/${slug}/';
const WIDTH = ${W};
const HEIGHT = ${H};

function computeInWorker(source, config) {
  return new Promise((resolve, reject) => {
    let worker;
    try {
      worker = new Worker(new URL('./halftone-worker.js', import.meta.url), { type: 'module' });
    } catch (e) {
      reject(e);
      return;
    }
    worker.onmessage = (e) => {
      worker.terminate();
      if (e.data.error) reject(new Error(e.data.error));
      else resolve(e.data.result);
    };
    worker.onerror = (e) => {
      worker.terminate();
      reject(e);
    };
    worker.postMessage({ source, config });
  });
}

export default function Halftone({
  src = ASSETS + 'source.${'${EXT}'}',
  mask = ${hasMask ? "ASSETS + 'mask.png'" : 'null'},
  poster = ASSETS + 'poster.${'${PEXT}'}',
  settings,
  ink = '${ink}',
  paper = ${paper ? `'${paper}'` : 'null'},
  fit = 'contain',
  position = 'center',
  alt = '',
  className,
  style,
  onReady,
}) {
  const canvasRef = useRef(null);
  const [result, setResult] = useState(null);
  const [drawn, setDrawn] = useState(false);
  const settingsKey = JSON.stringify(settings || {});
  const config = useMemo(() => ({ ...baseConfig, ...(settings || {}) }), [settingsKey]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const [img, m] = await Promise.all([loadImage(src), mask ? loadImage(mask) : null]);
      const source = prepareSource(img, m, config);
      let r;
      try {
        r = await computeInWorker(source, config);
      } catch (e) {
        r = computeHalftone(source, config); // no module workers: same result on the main thread
      }
      // a field with a sharp area blends the original image in (null otherwise)
      r.layers = fieldLayers(img, m, config);
      if (!cancelled) {
        setResult(r);
        if (onReady) onReady(r);
      }
    })().catch((e) => console.error('[Halftone]', e));
    return () => {
      cancelled = true;
    };
  }, [src, mask, config]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!result || !canvas) return;
    const draw = () => {
      drawHalftone(canvas, result, { ink, paper, fit, position, layers: result.layers });
      setDrawn(true);
    };
    draw();
    const ro = new ResizeObserver(draw);
    ro.observe(canvas);
    return () => ro.disconnect();
  }, [result, ink, paper, fit, position]);

  const layer = { position: 'absolute', inset: 0, width: '100%', height: '100%' };
  return (
    <div
      role="img"
      aria-label={alt}
      className={className}
      style={{ position: 'relative', aspectRatio: WIDTH + ' / ' + HEIGHT, ...style }}
    >
      {poster && (
        <img
          src={poster}
          alt=""
          aria-hidden="true"
          decoding="async"
          style={{ ...layer, objectFit: fit, objectPosition: position, opacity: drawn ? 0 : 1, transition: 'opacity .25s' }}
        />
      )}
      <canvas ref={canvasRef} aria-hidden="true" style={layer} />
    </div>
  );
}
`;
}

function readme({ slug, ext, pext, hasMask, W, H, summary }) {
  return `# Halftone web kit

Generated by Halftoner — ${W}×${H} — ${summary}.

This draws the halftone **live in the browser** from the source image and the
settings, with the same engine Halftoner uses. Nothing is pre-rendered except a
small poster shown while the dots compute.

## Files

\`\`\`
components/halftone/
  Halftone.jsx            React component (client component)
  halftone-engine.js      the engine — standalone ES module, no dependencies
  halftone-worker.js      runs the engine off the main thread
  halftone.config.json    every Halftoner setting for this design
public/halftone/${slug}/
  source.${ext}           the source image
${hasMask ? '  mask.png                subject mask (white = subject)\n' : ''}  poster.${pext}             instant placeholder, fades out once drawn
\`\`\`

Copy \`components/halftone\` into your components folder and \`public/halftone\`
into your static/public folder (served at \`/halftone/${slug}/\`). Works with
Next.js (App or Pages router) and Vite; needs React 18+.

## Use

\`\`\`jsx
import Halftone from '@/components/halftone/Halftone';

<Halftone alt="Two hands" className="w-full" />            // keeps the design's aspect ratio
<Halftone fit="cover" position="70% 50%" style={{ height: '100svh' }} />
<Halftone ink="currentColor" paper={null} />               // follow CSS color, transparent
<Halftone settings={{ cell: 12 }} />                       // override any setting live
<Halftone src="/other.jpg" />                              // same look, different image
\`\`\`

| Prop | Default | |
|---|---|---|
| \`src\` | \`/halftone/${slug}/source.${ext}\` | source image |
| \`mask\` | ${hasMask ? `\`/halftone/${slug}/mask.png\`` : '`null`'} | optional subject mask, white = subject |
| \`poster\` | \`/halftone/${slug}/poster.${pext}\` | placeholder until drawn (\`null\` to skip) |
| \`settings\` | — | partial overrides of \`halftone.config.json\` |
| \`ink\` / \`paper\` | from the design | colours; \`paper={null}\` is transparent |
| \`fit\` / \`position\` | \`contain\` / \`center\` | like \`object-fit\` / \`object-position\` |
| \`onReady\` | — | called with the computed result (\`{ W, H, pathD, glyphs, count }\`) |

Dots are computed once per source/settings (in a worker) and redrawn as vectors
on resize, so they stay sharp at any size and pixel density.

## Without React

\`\`\`js
import { loadImage, prepareSource, computeHalftone, drawHalftone, fieldLayers } from './halftone-engine.js';
const config = await (await fetch('/halftone/${slug}/halftone.config.json')).json();
const source = prepareSource(await loadImage('/halftone/${slug}/source.${ext}'), null, config);
const result = computeHalftone(source, config);
drawHalftone(document.querySelector('canvas'), result, { ink: '#000' });
\`\`\`

## Updating the look

Tweak the design in Halftoner and export a new kit, or edit
\`halftone.config.json\` by hand — every setting is a plain key.
`;
}

// ---------------------------------------------------------------- zip (store only)

const CRC = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(bytes) {
  let c = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) c = CRC[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

export function zip(files) {
  const enc = new TextEncoder();
  const now = new Date();
  const time = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1);
  const date = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate();
  const chunks = [], central = [];
  let offset = 0;
  for (const f of files) {
    const name = enc.encode(f.name);
    const data = typeof f.data === 'string' ? enc.encode(f.data) : f.data;
    const crc = crc32(data);
    const head = new DataView(new ArrayBuffer(30));
    head.setUint32(0, 0x04034b50, true);
    head.setUint16(4, 20, true);
    head.setUint16(6, 0x0800, true); // UTF-8 names
    head.setUint16(8, 0, true);      // stored
    head.setUint16(10, time, true);
    head.setUint16(12, date, true);
    head.setUint32(14, crc, true);
    head.setUint32(18, data.length, true);
    head.setUint32(22, data.length, true);
    head.setUint16(26, name.length, true);
    chunks.push(new Uint8Array(head.buffer), name, data);
    const cd = new DataView(new ArrayBuffer(46));
    cd.setUint32(0, 0x02014b50, true);
    cd.setUint16(4, 20, true);
    cd.setUint16(6, 20, true);
    cd.setUint16(8, 0x0800, true);
    cd.setUint16(10, 0, true);
    cd.setUint16(12, time, true);
    cd.setUint16(14, date, true);
    cd.setUint32(16, crc, true);
    cd.setUint32(20, data.length, true);
    cd.setUint32(24, data.length, true);
    cd.setUint16(28, name.length, true);
    cd.setUint32(42, offset, true);
    central.push(new Uint8Array(cd.buffer), name);
    offset += 30 + name.length + data.length;
  }
  const cdSize = central.reduce((n, c) => n + c.length, 0);
  const end = new DataView(new ArrayBuffer(22));
  end.setUint32(0, 0x06054b50, true);
  end.setUint16(8, files.length, true);
  end.setUint16(10, files.length, true);
  end.setUint32(12, cdSize, true);
  end.setUint32(16, offset, true);
  return new Blob([...chunks, ...central, new Uint8Array(end.buffer)], { type: 'application/zip' });
}

// ---------------------------------------------------------------- assets

async function encode(canvas, type, quality) {
  const blob = await new Promise((r) => canvas.toBlob(r, type, quality));
  return { bytes: new Uint8Array(await blob.arrayBuffer()), type: blob.type };
}

// Poster: the finished design at up to 1600px wide.
async function poster(result, s) {
  const k = Math.min(1, 1600 / result.W);
  const c = document.createElement('canvas');
  c.width = Math.round(result.W * k);
  c.height = Math.round(result.H * k);
  drawDesign(c.getContext('2d', { willReadFrequently: true }), result, s, k, false);
  return encode(c, 'image/webp', 0.85);
}

export async function exportKit({ state, source, mask, result, slug, summary }) {
  // photos as WebP, text / line art as PNG (browsers without WebP encoding fall back to PNG)
  const src = await encode(source, state.sourceType === 'text' ? 'image/png' : 'image/webp', 0.92);
  const ext = src.type === 'image/webp' ? 'webp' : 'png';
  const post = await poster(result, state);
  const pext = post.type === 'image/webp' ? 'webp' : 'png';
  const hasMask = !!mask;
  const ink = state.colors === 'wb' ? '#ffffff' : '#000000';
  const paper = state.colors === 'wb' ? '#000000' : '#ffffff';
  const meta = { W: result.W, H: result.H, slug, hasMask, ink, paper, summary, ext, pext };

  const files = [
    { name: 'README.md', data: readme(meta) },
    { name: 'components/halftone/Halftone.jsx', data: component(meta).replace('${EXT}', ext).replace('${PEXT}', pext) },
    { name: 'components/halftone/halftone-engine.js', data: await bundleEngine() },
    { name: 'components/halftone/halftone-worker.js', data: WORKER },
    { name: 'components/halftone/halftone.config.json', data: JSON.stringify(state, null, 2) + '\n' },
    { name: `public/halftone/${slug}/source.${ext}`, data: src.bytes },
    { name: `public/halftone/${slug}/poster.${pext}`, data: post.bytes },
  ];
  if (hasMask) files.push({ name: `public/halftone/${slug}/mask.png`, data: (await encode(mask, 'image/png')).bytes });
  return zip(files);
}
